### ISSUE TITLE
Question about "FloatingPointError: loss bacame infinite or NaN at iteration"

### ISSUE THREAD

**Issue by Simon-Stma** [GuangxingHan/Meta-Faster-R-CNN#10]
Thank you very much for your patient answer before. When using my own dataset (public dataset), I often have the problem "FloatingPointError: loss bacame infinite or NaN at iteration" in the first stage of training (the baseline is FewX) (but this problem does not occur sometimes, so is it due to random sampling?). I prepared all my datasets with the code provided in your paper and the cited prepare_voc_few_shot.py in the same format as you suggested, probably due to the small number of datasets (800), I used 4 GPU V100, Img_pre_batch=8 (two on each GPU) for I tried to adjust the learning rate to 0.00001 for the first phase of meta-training, and this error also occurs, and after checking the FewX issue, I also tried to upgrade detectron2 from 0.2.1 to 0.3, but this problem still occurs. I would like to add that the problem does not occur when I train the number of arguments as default (15000,20000), but in the second small stage of the first phase (adding fusion network into meta-rcnn and meta-classifier), the same error occurs again, and there is no way to solve it by adjusting the learning rate. I would like to consult you to see if there is any good advice.

**Comment by GuangxingHan** [comment]
Thanks again for your interest in our work. 
This is an interesting question. I also encountered it before, and solved this problem by increasing batch_size from 4 to 8 as in this repo. 
Did you have the same problem on MSCOCO or VOC?
How do you solve this problem for the fewx baseline? simply using the default training stage of (15000,20000)?

**Comment by Simon-Stma** [comment]
I did not try the MSCOCO and VOC datasets, I only converted my own dataset to VOC for the experiment; I just tried again, all parameters are default training rounds is 20000, learning rate is 0.002, IMS_PRE_BATCH is 8, a total of four cards, and found that it does run successfully (but in the test at the end of the fewx , map and other indicators are almost close to 0, is there an overfitting phenomenon?) , and the second stage will still appear loss for NaN problem, only he appeared Nan place in iteration3, rather than the previous 1.

**Comment by Simon-Stma** [comment]
To add to this, I just conducted a test with multiple sets of different training rounds and found that when I adjusted back to the default parameters (20,000 rounds), he had the NaN problem again, whereas before it was able to run successfully. This phenomenon is what I also found before, sometimes it can run successfully, sometimes not (under the same set of parameters). So is it caused by the random loading of data from the dataset dataloader? Also I would like to say that I did not load the ImageNet pre-training model and the initial weights of the model were initialized randomly, is it possible that the dataset itself is too small in number and there is no initial weight to guide it, so it does not converge well and thus the loss is NaN?

**Comment by GuangxingHan** [comment]
I see. Please use the ImageNet pre-training weight to initialize the model. We did all the experiment using ImageNet pre-trained ResNet-101, including the FewX baseline. It is pretty hard to train Faster R-CNN from scratch.

**Comment by Simon-Stma** [comment]
I also just tried to download the ImageNet pre-training model offline, found that this is indeed the reason, and according to my own dataset to adjust the parameters accordingly, indicators in the first stage are also normal, thank you for your reply :)

**Comment by GuangxingHan** [comment]
Great to know that it works. Thanks for the feedback.
