### ISSUE TITLE
Questions about backbone on meta-training

### ISSUE THREAD

**Issue by Simon-Stma** [GuangxingHan/Meta-Faster-R-CNN#16]
Thank you for your previous patient answer, after studying your work for some time, I have some questions, that is, why not use faster-rcnn-fpn but use faster-r-cnn-c4, is it because of the memory occupation problem? Can the backbone of meta-training be changed to faster-rcnn-fpn?

**Comment by GuangxingHan** [comment]
We have tried this before. Unfortunately this does not work, and the performance is much worse. We have not got a solution for this so far.

**Comment by MrCrightH** [comment]
meta_training_coco_resnet101_stage_2.yaml

**Comment by Simon-Stma** [comment]
Thanks for your reply!
