### ISSUE TITLE
The inference scripts

### ISSUE THREAD

**Issue by shanguangcv** [GuangxingHan/Meta-Faster-R-CNN#2]
Hello, I only find the training scripts  in Readme. Does this mean that inference will be performed automatically after the training?

**Comment by GuangxingHan** [comment]
Yes, the evaluation will be automatically done after training.

You can also do the evaluation manually. The example script is 
```
CUDA_VISIBLE_DEVICES=0,1,2,3 python3 fsod_train_net.py --num-gpus 4 --dist-url auto \
	--config-file configs/fsod/meta_training_coco_resnet101_stage_1.yaml  --eval-only MODEL.WEIGHTS [Model_Path] 2>&1 | tee log/meta_training_coco_resnet101_stage_1.txt
```
The difference between the training script is `--eval-only MODEL.WEIGHTS [Model_Path]`
