### ISSUE TITLE
Why is the weight file generated by the second script not used？

### ISSUE THREAD

**Issue by LiangYang666** [GuangxingHan/Meta-Faster-R-CNN#23]
The second script "faster_rcnn_with_fpn_XX_base_classes_branch.sh" generate a weight file, but the third script does not use this weight file, what does the second script do？

**Comment by GuangxingHan** [comment]
The second step is simply used to train the base class detection head while freezing the feature backbone. 
The third step is to fine-tune the novel class detection head while freezing the feature backbone. 
The feature backbone is shared in the second and third step, which is pre-trained from the first step.

**Comment by LiangYang666** [comment]
Thank you, does  it mean I just need run the first and third step  if I want eval the full  model on the novel class

**Comment by GuangxingHan** [comment]
Yes, you are right.

**Comment by LiangYang666** [comment]
Thank you, 
![image](http://n.sinaimg.cn/sinakd2020811s/726/w363h363/20200811/dddc-ixreehn6439078.gif)
