### ISSUE TITLE
Questions about VOC dataset partitioning

### ISSUE THREAD

**Issue by Simon-Stma** [GuangxingHan/Meta-Faster-R-CNN#3]
Your work is interesting and inspiring. After referring to your paper, I would like to ask if the three ways of classifying novel classes used in the paper for the VOC dataset are based on your own experience, or to enrich the experimental results, etc. Also when dealing with my own dataset (which has been converted to VOC format), is it possible to define the division of novel classes in my own way, e.g., to take only one custom way instead of three.

**Comment by GuangxingHan** [comment]
Thanks for your interest in our work!
- We follow the previous works [1,2] to use the three base/novel class splits in the VOC dataset for fair comparison. Please refer to [1,2] for more details about how to build up this FSOD benchmark. (It seems that they do random class partitions for three times)

[1]. Kang, Bingyi, Zhuang Liu, Xin Wang, Fisher Yu, Jiashi Feng, and Trevor Darrell. "Few-shot object detection via feature reweighting." In Proceedings of the IEEE/CVF International Conference on Computer Vision, pp. 8420-8429. 2019.
[2]. Wang, Xin, Thomas E. Huang, Trevor Darrell, Joseph E. Gonzalez, and Fisher Yu. "Frustratingly simple few-shot object detection." arXiv preprint arXiv:2003.06957 (2020).

- Yes, you can define your own class partitions in your dataset. One way is to do random class partitions as [1,2] multiple times which can test the robustness of the model (multiple is better than one). Another way is that you can select the few-shot novel classes according to the number of training examples,  and use these true rare classes as novel classes.

**Comment by Simon-Stma** [comment]
Thank you for your reply, your reply is very helpful to me, have a good work！
