### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by beixiansheng333** [GuangxingHan/Meta-Faster-R-CNN#47]
When I run sh scripts/meta_training_pascalvoc_split1_resnet101_multi_stages.sh  ，When I start training but no log file is generated, what is the cause?

**Comment by GuangxingHan** [comment]
Can you post the training log here?

**Comment by beixiansheng333** [comment]
The above problems have been solved, but I have a new problem. TypeError: __init__() got an unexpected keyword argument 'first_stride'. Is it a version incompatibility problem?

**Comment by beixiansheng333** [comment]
My problem has been solved, thank you very much.

通过 [Proton Mail](https://proton.me/mail/home) 安全邮箱发送。

2024年9月13日 星期五 上午 1:27，Guangxing Han ***@***.***> 来信：
